name: Auto deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/package.json'
  pull_request:
    branches:
      - main
jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'Upgrade to')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm version patch -m "Upgrade to %s due to dependency updates"
      - run: git push origin main
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
